### ISSUE TITLE
Unable to convert Readme file data of AUBIGroups.xcodeproj to c# project through Project Translator.

### ISSUE THREAD

**Issue by Arpit360** [rzaitov/sample-translator#1]
When we convert 
Screeencast: http://www.screencast.com/t/2tji1f1su
Environment Info: https://gist.github.com/Arpit360/25e992c8cb8213cbd619

**Comment by olegoid** [comment]
I don’t think that this is a bug. Since Apple owns sample’s copyrights we can’t just copy/paste their readme in ported version of sample because it’s illegal.
