### ISSUE TITLE
[Porting Samples- ImageInverterCreatingActionExtensions]:  Project Translator does  not create c# solution on conversion of Xcode project.

### ISSUE THREAD

**Issue by Arpit360** [rzaitov/sample-translator#7]
Issues: 
In  Xcode the folder hierarchy is :
Source Folder
 Solution name
    Project1
    Project2 

but after converting it in c# project it breaks this Xcode hierarchy and becomes
Destination folder
     Project1
     Project2

Solution is missing from this hierarchy and because of this we are unable to load both project concurrently.

Screencast: http://www.screencast.com/t/X3lg0bQXx

**Comment by olegoid** [comment]
Fixed in d0b771dbc16e838a2d65e04d4fddcd54d0088870
